export const GET_CURRENCIES = 'GET_CURRENCIES';
export const CHANGE_BASE_CURRENCY = 'CHANGE_BASE_CURRENCY';
export const ADD_CURRENCY_TO_FAVORITES = 'ADD_CURRENCY_TO_FAVORITES';
export const REMOVE_CURRENCY_FROM_FAVORITES = 'REMOVE_CURRENCY_FROM_FAVORITES';
export const GET_CONVERTED_CURRENCIES = 'GET_CONVERTED_CURRENCIES';
